import { CalendarDays, CheckCircle2, FileText, Home, MessageSquareText, PackageCheck, Settings, TrendingUp, UserRound, WalletCards } from "lucide-react";
import { PortalShell, type PortalNavItem } from "@/components/portal/portal-shell";
import { OrderChat } from "@/components/portal/order-chat";
import { requireRole } from "@/lib/auth/require-role";
import { Badge } from "@/components/ui/badge";

export const dynamic = "force-dynamic";

const nav: PortalNavItem[] = [{ label: "Overview", href: "/dashboard", icon: Home }, { label: "My orders", href: "/dashboard/orders/demo-order", icon: PackageCheck, active: true }, { label: "Messages", href: "#messages", icon: MessageSquareText, badge: "2" }, { label: "Sessions", href: "#sessions", icon: CalendarDays }, { label: "Progress", href: "#progress", icon: TrendingUp }, { label: "Coaches", href: "/coaches", icon: UserRound }, { label: "Billing", href: "/dashboard#billing", icon: WalletCards }, { label: "Settings", href: "/dashboard#settings", icon: Settings }];
interface Props { params: Promise<{ id: string }> }
export default async function OrderWorkspacePage({ params }: Props) { const user = await requireRole(["customer"]); const { id } = await params; return <PortalShell user={user} label="Customer" navigation={nav}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-3"><p className="text-[0.62rem] font-bold tracking-[0.13em] text-amber uppercase">Order · {id === "demo-order" ? "HG-2084" : id}</p><Badge tone="cyan">In progress</Badge></div><h1 className="mt-3 text-3xl font-black">Carry decision framework</h1><p className="mt-2 text-sm text-mist">Live coaching · 2 sessions · 1 replay review</p></div><button className="rounded-full border border-white/15 px-4 py-2.5 text-xs font-bold text-mist">Request support</button></div><div className="mt-7 grid gap-5 xl:grid-cols-[1fr_300px]"><div id="messages"><OrderChat /></div><aside className="space-y-4"><section className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><p className="text-sm font-black">Order progress</p><ol className="mt-5 space-y-4">{[["Payment confirmed", true], ["Coach assigned", true], ["Replay delivered", true], ["Live session", false], ["Completion review", false]].map(([label, complete]) => <li key={label as string} className="flex items-center gap-3 text-xs"><span className={`grid size-5 place-items-center rounded-full border ${complete ? "border-cyan/30 bg-cyan/10 text-cyan" : "border-white/15 text-mist"}`}>{complete ? <CheckCircle2 className="size-3" /> : null}</span>{label as string}</li>)}</ol></section><section id="sessions" className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><CalendarDays className="size-4 text-cyan" /><p className="mt-3 text-[0.6rem] font-bold tracking-wider text-mist uppercase">Next session</p><p className="mt-2 text-sm font-bold">Friday, July 17 · 7:30 PM</p><p className="mt-1 text-[0.62rem] text-mist">America/Toronto · 60 minutes</p><button className="mt-4 w-full rounded-full bg-white/[0.07] py-2.5 text-xs font-bold">View meeting link</button></section><section className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><FileText className="size-4 text-amber" /><p className="mt-3 text-sm font-black">Latest deliverable</p><p className="mt-2 text-xs text-mist">Replay analysis · 3 priorities</p><button className="mt-4 text-xs font-bold text-amber">Open deliverable →</button></section></aside></div></PortalShell>; }
