import { CalendarDays, CheckCircle2, Home, MessageSquareText, PackageCheck, Radio, Settings, Trophy, UserRound, WalletCards } from "lucide-react";
import { PortalShell, type PortalNavItem } from "@/components/portal/portal-shell";
import { OrderChat } from "@/components/portal/order-chat";
import { requireRole } from "@/lib/auth/require-role";
import { Badge } from "@/components/ui/badge";
import { getCustomerConversationId, getCustomerOrder } from "@/lib/portal/customer-orders";

export const dynamic = "force-dynamic";

const nav: PortalNavItem[] = [{ label: "Overview", href: "/dashboard", icon: Home }, { label: "My boosts", href: "/dashboard/orders", icon: PackageCheck, active: true }, { label: "Messages", href: "#messages", icon: MessageSquareText }, { label: "Queue schedule", href: "#schedule", icon: CalendarDays }, { label: "Progress", href: "#progress", icon: Trophy }, { label: "Boosters", href: "/boosters", icon: UserRound }, { label: "Billing", href: "/dashboard/billing", icon: WalletCards }, { label: "Settings", href: "/dashboard#settings", icon: Settings }];
interface Props { params: Promise<{ id: string }> }
export default async function OrderWorkspacePage({ params }: Props) {
  const user = await requireRole(["customer"]); const { id } = await params;
  const order = id === "demo-order" ? null : await getCustomerOrder(user.id, id);
  const conversationId = order ? await getCustomerConversationId(user.id, id) : null;
  const isDemo = id === "demo-order";
  const reference = order?.publicReference ?? "HG-4281";
  const serviceName = order?.serviceName ?? "MMR Boost";
  const scope = order?.scope ?? "Legend III → Ancient I · +500 MMR";
  const state = order?.status?.replaceAll("_", " ") ?? "in progress";
  const progress = order?.progressPercent ?? 70;
  const progressDetail = order?.totalMilestones ? `${order.completedMilestones} of ${order.totalMilestones} milestones complete` : isDemo ? "70% of configured delivery scope tracked" : "Operations will add milestones after matching";
  return <PortalShell user={user} label="Customer" navigation={nav}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-3"><p className="text-[0.62rem] font-bold tracking-[0.13em] text-amber uppercase">{serviceName} · {reference}</p><Badge tone="cyan">{state}</Badge></div><h1 className="mt-3 text-3xl font-black">{scope}</h1><p className="mt-2 text-sm text-mist">{progressDetail}</p></div><button className="rounded-full border border-white/15 px-4 py-2.5 text-xs font-bold text-mist">Request support</button></div><div className="mt-7 grid gap-5 xl:grid-cols-[1fr_300px]"><div id="messages"><OrderChat conversationId={conversationId} currentUserId={user.id} /></div><aside className="space-y-4"><section id="progress" className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><p className="text-sm font-black">Delivery progress</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/[0.08]"><div className="h-full bg-gradient-to-r from-crimson via-amber to-cyan" style={{ width: `${progress}%` }} /></div><p className="mt-2 text-[0.6rem] text-mist">{progressDetail}</p><ol className="mt-5 space-y-4">{[["Payment confirmed", true], ["Operations matching", ["matching", "coach_assigned", "awaiting_customer", "in_progress", "delivery_submitted", "customer_review", "completed"].includes(order?.status ?? "in_progress")], ["Delivery milestones", progress > 0], ["Completion review", ["customer_review", "completed"].includes(order?.status ?? "")]].map(([label, complete]) => <li key={label as string} className="flex items-center gap-3 text-xs"><span className={`grid size-5 place-items-center rounded-full border ${complete ? "border-cyan/30 bg-cyan/10 text-cyan" : "border-white/15 text-mist"}`}>{complete ? <CheckCircle2 className="size-3" /> : null}</span>{label as string}</li>)}</ol></section><section id="schedule" className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><CalendarDays className="size-4 text-cyan" /><p className="mt-3 text-[0.6rem] font-bold tracking-wider text-mist uppercase">Queue schedule</p><p className="mt-2 text-sm font-bold">Coordinate in your order chat</p><p className="mt-1 text-[0.62rem] text-mist">Your approved queue windows and changes stay on this order.</p><button className="mt-4 w-full rounded-full bg-white/[0.07] py-2.5 text-xs font-bold">Request a schedule update</button></section><section className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><Radio className="size-4 text-amber" /><p className="mt-3 text-sm font-black">Delivery team</p><p className="mt-2 text-xs text-mist">A compatible Dota 2 specialist is assigned after operations confirms your order.</p><button className="mt-4 text-xs font-bold text-amber">Open booster directory →</button></section></aside></div></PortalShell>;
}
