import { BarChart3, CalendarDays, CircleDollarSign, ClipboardCheck, Clock3, Home, MessageSquareText, PackageSearch, Radio, Settings, Star, Trophy, UsersRound } from "lucide-react";
import { PortalShell, type PortalNavItem } from "@/components/portal/portal-shell";
import { MetricCard } from "@/components/portal/metric-card";
import { AvailabilityToggle, AssignmentDecision } from "@/components/portal/booster-actions";
import { requireRole } from "@/lib/auth/require-role";
import { getCoachOperations } from "@/lib/portal/coach-operations";
import { formatCurrency } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";

export const dynamic = "force-dynamic";

const nav: PortalNavItem[] = [
  { label: "Overview", href: "/coach", icon: Home, active: true },
  { label: "Assignments", href: "/coach#assignments", icon: PackageSearch },
  { label: "Active boosts", href: "/coach#orders", icon: ClipboardCheck },
  { label: "Messages", href: "/coach#messages", icon: MessageSquareText },
  { label: "Queue schedule", href: "/coach#schedule", icon: CalendarDays },
  { label: "Customers", href: "/coach#customers", icon: UsersRound },
  { label: "Earnings", href: "/coach#earnings", icon: CircleDollarSign },
  { label: "Performance", href: "/coach#performance", icon: BarChart3 },
  { label: "Settings", href: "/coach#settings", icon: Settings }
];

export default async function CoachDashboardPage() {
  const user = await requireRole(["coach"]);
  const operations = await getCoachOperations(user.id);
  if (!operations) return <PortalShell user={user} label="Booster" navigation={nav}><section className="max-w-xl py-8"><p className="text-[0.62rem] font-bold tracking-[0.13em] text-amber uppercase">Booster setup</p><h1 className="mt-3 text-3xl font-black">Your booster profile is still being prepared.</h1><p className="mt-3 text-sm leading-6 text-mist">Operations needs to complete your profile before assignments, availability, and earnings can appear here.</p></section></PortalShell>;
  const active = operations.assignments.filter((assignment) => assignment.status === "accepted");
  const pending = operations.assignments.filter((assignment) => assignment.status === "assigned");
  const completedMilestones = active.reduce((sum, assignment) => sum + assignment.completedMilestones, 0);
  const totalMilestones = active.reduce((sum, assignment) => sum + assignment.totalMilestones, 0);
  return <PortalShell user={user} label="Booster" navigation={nav}>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[0.62rem] font-bold tracking-[0.13em] text-cyan uppercase">Booster operations</p><h1 className="mt-2 text-3xl font-black">Your Dota delivery board.</h1><p className="mt-2 text-sm text-mist">Accept compatible assignments, keep availability current, and follow live order milestones.</p></div><AvailabilityToggle initialAvailable={operations.isAvailable} /></div>
    <div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={ClipboardCheck} label="Active boosts" value={String(operations.activeCount)} detail={operations.activeCount ? "Accepted assignments" : "No active delivery"} tone="red" /><MetricCard icon={CalendarDays} label="Needs response" value={String(operations.pendingCount)} detail={operations.pendingCount ? "Review assignments below" : "No pending assignment"} tone="cyan" /><MetricCard icon={Trophy} label="Milestones logged" value={totalMilestones ? `${completedMilestones} / ${totalMilestones}` : "—"} detail={totalMilestones ? "Across active boosts" : "No tracked milestones"} tone="gold" /><MetricCard icon={CircleDollarSign} label="Reserved earnings" value={formatCurrency(operations.earningsReserved)} detail={operations.earningsReleased ? `${formatCurrency(operations.earningsReleased)} released` : "Released after review"} /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><section id="orders" className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-black">Active boosts</h2><p className="mt-1 text-[0.62rem] text-mist">Accepted customer-controlled delivery scopes.</p></div><span className="rounded-full border border-cyan/20 bg-cyan/[0.06] px-2.5 py-1 text-[0.58rem] font-bold text-cyan uppercase">{active.length} live</span></div>{active.length ? <div className="mt-5 divide-y divide-white/[0.07]">{active.map((assignment) => <article key={assignment.id} className="grid gap-4 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="text-[0.58rem] font-bold tracking-wider text-mist uppercase">{assignment.publicReference}</p><Badge tone="cyan">{assignment.totalMilestones ? `${assignment.progressPercent}% tracked` : "Setup pending"}</Badge></div><h3 className="mt-2 text-sm font-bold">{assignment.serviceName}</h3><p className="mt-1 text-[0.62rem] text-mist">{assignment.scope}</p></div><span className="rounded-full border border-white/10 px-3 py-2 text-center text-[0.62rem] font-bold text-mist">Private workspace</span></article>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-white/[0.13] px-4 py-8 text-center text-xs text-mist">Accepted assignments appear here after you review them.</div>}</section><section id="performance" className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><h2 className="text-sm font-black">Profile performance</h2><div className="mt-5 grid grid-cols-2 gap-3">{[[Star, operations.averageRating ? operations.averageRating.toFixed(2) : "—", "Average rating"], [Radio, operations.isAvailable ? "Live" : "Paused", "Availability"], [ClipboardCheck, String(operations.completedSessions), "Completed sessions"], [Clock3, operations.currentRank, "Current rank"]].map(([Icon, value, label]) => { const PerformanceIcon = Icon as typeof Star; return <div key={label as string} className="rounded-xl border border-white/[0.07] p-4"><PerformanceIcon className="size-4 text-cyan" /><p className="mt-4 text-xl font-black">{value as string}</p><p className="mt-1 text-[0.58rem] text-mist">{label as string}</p></div>; })}</div><p className="mt-4 text-[0.6rem] leading-5 text-mist">{operations.tier} roster · availability is visible to operations when matching new orders.</p></section></div>
    <section id="assignments" className="mt-5 rounded-2xl border border-white/[0.08] bg-black/15 p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-black">Assignment review</h2><p className="mt-1 text-[0.62rem] text-mist">Accept only scopes you can complete safely and professionally.</p></div><Badge tone="gold">{pending.length} awaiting response</Badge></div>{pending.length ? <div className="mt-5 grid gap-3 lg:grid-cols-3">{pending.map((assignment) => <article key={assignment.id} className="rounded-xl border border-white/[0.08] p-4"><p className="text-[0.58rem] font-bold tracking-wider text-mist uppercase">{assignment.publicReference}</p><p className="mt-3 text-xs font-black">{assignment.serviceName}</p><p className="mt-2 text-[0.62rem] text-mist">{assignment.scope}</p><div className="mt-5 flex items-center justify-between"><span className="text-sm font-black">{formatCurrency(assignment.compensationAmount)}</span><span className="text-[0.58rem] text-mist">Reserved on acceptance</span></div><AssignmentDecision assignmentId={assignment.id} /></article>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-white/[0.13] px-4 py-8 text-center text-xs text-mist">No compatible assignments are waiting for a response.</div>}</section>
  </PortalShell>;
}
