import type { Metadata } from "next";
import { BadgeCheck, CalendarCheck, MessageCircleMore, Radio, ShieldCheck, WalletCards } from "lucide-react";
import { PageHero } from "@/components/ui/page-hero";
import { CoachApplicationForm } from "@/components/forms/coach-application-form";

export const metadata: Metadata = { title: "Work With Us — Booster Applications", description: "Apply to join Highground as a verified Dota 2 self-play booster.", alternates: { canonical: "/work-with-us" } };
const expectations = [[BadgeCheck, "Demonstrable high-rank play", "Provide public rank history that reviewers can verify."], [MessageCircleMore, "Clear queue communication", "Make concise calls without belittling or overwhelming customers."], [CalendarCheck, "Reliable availability", "Keep queue windows current and give notice when plans change."], [Radio, "Stable regional setup", "Use approved servers and maintain a reliable connection for assigned queues."], [ShieldCheck, "Strict account boundaries", "Never request credentials, codes, remote access, or control of a customer account."], [WalletCards, "Transparent earnings", "See compensation before accepting an assignment."]] as const;

export default function WorkWithUsPage() {
  return <><PageHero eyebrow="Join the roster" title="Play at a high level. Deliver like a professional." description="We are building a verified roster of skilled Dota 2 players who queue reliably, communicate clearly, and respect customer account boundaries." /><section className="section-pad container-shell"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{expectations.map(([Icon, title, body]) => <article key={title} className="rounded-2xl border border-white/[0.08] bg-panel/60 p-5"><Icon className="size-5 text-cyan" /><h2 className="mt-5 font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-mist">{body}</p></article>)}</div><div className="mt-16 grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><span className="eyebrow">Application process</span><ol className="mt-7 space-y-5">{["Submit your rank history and service background", "Complete identity, rank, and conduct verification", "Communication and queue-readiness assessment", "Interview and optional trial assignment", "Approval, onboarding, and booster invitation"].map((step, index) => <li key={step} className="flex gap-4 text-sm"><span className="grid size-7 shrink-0 place-items-center rounded-full border border-crimson/30 bg-crimson/10 text-[0.65rem] font-black text-crimson">{index + 1}</span><span className="pt-1 leading-5">{step}</span></li>)}</ol><div className="mt-9 rounded-2xl border border-amber/20 bg-amber/[0.06] p-5 text-xs leading-6 text-[#c6b38f]">Submitting an application does not guarantee approval or assignment volume. Compensation varies by service, tier, bracket, and agreed scope.</div></div><div><div className="mb-7"><span className="eyebrow">Booster application</span><h2 className="mt-5 text-3xl font-black">Show us how you operate.</h2></div><CoachApplicationForm /></div></div></section></>;
}
