import type { Metadata } from "next";
import { notFound } from "next/navigation";

const legalPages = {
  terms: { title: "Terms of Service", intro: "These placeholder terms describe the intended self-play boosting relationship and must be reviewed by qualified legal counsel before launch.", sections: [["Service model", "Highground provides a marketplace and private workspace for customer-controlled party-queue services. Customers play every match on their own account; approved boosters play on their own accounts."], ["No guarantees", "Packages define service scope, scheduling, or assisted wins. No MMR, rank, win rate, match outcome, or other performance result is promised or guaranteed."], ["Eligibility and publisher rules", "Services may be limited, changed, paused, or declined when rank compatibility, party eligibility, regional requirements, matchmaking rules, or publisher policies do not permit delivery."], ["Account safety", "Users must never request or share Steam passwords, authentication codes, recovery codes, device sessions, or remote account access through the platform."], ["Conduct", "Harassment, discriminatory language, fraud, credential requests, matchmaking manipulation, and attempts to bypass platform safety controls are prohibited."]] },
  privacy: { title: "Privacy Policy", intro: "This placeholder explains the intended data practices and requires professional privacy review before production launch.", sections: [["Data we process", "Account details, boost requirements, rank and region preferences, messages, scheduling information, payment references, support records, and product telemetry necessary to operate the service."], ["Sensitive exclusions", "Highground does not request or intentionally process Steam passwords, authentication codes, recovery codes, remote access tokens, or raw payment card details."], ["Private media", "Order attachments are stored privately and accessed through time-limited signed URLs by authorized conversation members."], ["Your choices", "Users can manage notification preferences and may request access, correction, or deletion subject to legal and operational retention requirements."]] },
  refunds: { title: "Refund Policy", intro: "This placeholder outlines an intended review framework. Final eligibility rules require legal and payment-provider review.", sections: [["Eligibility", "Refund eligibility depends on assisted matches completed, queue time reserved, progress already delivered, and the documented reason for the request."], ["Review", "Support may review order requirements, match milestones, scheduling records, messages, and relevant workspace evidence before deciding."], ["Outcomes", "An eligible case may result in rescheduling, booster reassignment, platform credit, a partial refund, or a full refund."], ["Processing", "Approved refunds are returned through the original payment method with an idempotent Stripe request and mandatory internal audit reason. Bank processing times vary."]] },
  disclaimer: { title: "Service Disclaimer", intro: "Highground is an independent service and is not affiliated with or endorsed by Valve Corporation.", sections: [["No performance guarantee", "Ranked outcomes depend on matchmaking, customer play, teammates, opponents, game updates, party eligibility, and factors outside any booster’s control."], ["Customer control", "Customers play on and control their own accounts. Boosters join eligible queues from their own accounts and must not request customer account access."], ["Third-party marks", "Dota and Steam are trademarks of their respective owner and are used only to identify the game and platform relevant to the service."], ["Policy changes", "Game publisher rules and regional requirements may change. Services may be adjusted or withdrawn to maintain compliance."]] },
  "community-guidelines": { title: "Community & Communication Guidelines", intro: "Every private workspace should be useful, respectful, and safe.", sections: [["Respect", "Coordinate matches without insulting another person. Harassment and discriminatory content are prohibited."], ["Privacy", "Do not share another person’s private information, conversation media, or signed links outside the authorized workspace."], ["Account security", "Never ask for or share credentials, Steam Guard codes, recovery codes, device sessions, or remote access."], ["Reporting", "Report unsafe or abusive messages through the workspace so authorized staff can review and document the response."]] },
  "acceptable-use": { title: "Acceptable Use Policy", intro: "Use Highground only for approved customer-controlled services and related communication.", sections: [["Allowed use", "Eligible party queue, service configuration, progress tracking, scheduling, support, reviews, and approved delivery communication."], ["Prohibited use", "Credential collection, account access, fraud, bots, scripts, cheats, exploits, match fixing, intentional feeding, malware, harassment, payment circumvention, and illegal content."], ["Media", "Upload only files you are authorized to share and that meet the stated file type and size limits."], ["Enforcement", "Highground may restrict content, cancel an ineligible service, or suspend access when necessary to protect users, the platform, game integrity, or legal compliance."]] },
  cookies: { title: "Cookie Policy", intro: "This placeholder describes essential session cookies and optional analytics choices.", sections: [["Essential cookies", "Secure cookies maintain authentication, prevent abuse, and preserve settings necessary to provide the service."], ["Analytics", "Optional analytics measure product usage without sending private chat content, payment data, or direct personal identifiers."], ["Preferences", "Where required, non-essential analytics are disabled until the user provides consent."], ["Control", "Browser settings can remove cookies, but disabling essential cookies may prevent sign-in and private workspace features."]] },
  "provider-agreement": { title: "Booster Provider Agreement", intro: "This placeholder outlines booster obligations and requires professional legal review before onboarding providers.", sections: [["Independent service", "Approved boosters deliver assigned customer-controlled party-queue services according to published standards and agreed compensation."], ["Account boundaries", "Boosters must play from their own accounts, must not request customer credentials or remote access, and must protect private workspace information."], ["Game integrity", "Boosters must not use bots, scripts, cheats, exploits, intentional feeding, match fixing, or prohibited matchmaking manipulation."], ["Quality", "Boosters are expected to communicate professionally, attend confirmed queue windows, and document agreed milestones."], ["Compensation", "Booster payment is released after service completion and the applicable review period, subject to refunds, disputes, and platform terms."]] }
} as const;

interface Props { params: Promise<{ slug: string }> }
export function generateStaticParams() { return Object.keys(legalPages).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const page = legalPages[slug as keyof typeof legalPages]; return page ? { title: page.title, robots: { index: false, follow: true } } : {}; }
export default async function LegalPage({ params }: Props) { const { slug } = await params; const page = legalPages[slug as keyof typeof legalPages]; if (!page) notFound(); return <section className="container-shell py-20"><span className="eyebrow">Legal placeholder</span><h1 className="display-type mt-6 text-6xl font-black uppercase md:text-8xl">{page.title}</h1><p className="mt-6 max-w-3xl text-base leading-7 text-mist">{page.intro}</p><div className="mt-14 max-w-3xl space-y-10">{page.sections.map(([title, body]) => <section key={title}><h2 className="text-xl font-black">{title}</h2><p className="mt-3 text-sm leading-7 text-mist">{body}</p></section>)}</div><p className="mt-14 max-w-3xl rounded-xl border border-amber/20 bg-amber/[0.06] p-4 text-xs leading-6 text-[#c6b38f]">Draft product copy only. Replace with a jurisdiction-specific version reviewed by qualified counsel and confirm current publisher and payment-provider requirements before accepting production users or payments.</p></section>; }
