import type { Metadata } from "next";
import { Check, CreditCard, LifeBuoy, MessagesSquare, Search, Star } from "lucide-react";
import { PageHero } from "@/components/ui/page-hero";
import { LinkButton } from "@/components/ui/button";

export const metadata: Metadata = { title: "How Dota 2 Coaching Works", description: "See how service selection, secure payment, coach matching, scheduling, delivery, approval, reviews, and support work.", alternates: { canonical: "/how-it-works" } };
const phases = [[Search, "Define the work", "Choose a service and tell us your role, region, schedule, and improvement goal."], [CreditCard, "Pay securely", "The server verifies the price, then Stripe hosts checkout. An order is marked paid only after a signed webhook."], [MessagesSquare, "Enter your workspace", "A verified coach is assigned manually and your private order conversation opens."], [Star, "Review the outcome", "Approve deliverables, request support if needed, and leave verified feedback after completion."]] as const;

export default function HowItWorksPage() {
  return <><PageHero eyebrow="How it works" title="From a vague goal to a useful next game." description="A transparent delivery flow designed around account safety, clear expectations, and work you can review." /><section className="section-pad container-shell"><div className="grid gap-5 lg:grid-cols-4">{phases.map(([Icon, title, body], index) => <article key={title} className="surface rounded-[1.5rem] p-6"><div className="flex items-center justify-between"><Icon className="size-5 text-cyan" /><span className="text-xs font-black text-crimson">0{index + 1}</span></div><h2 className="mt-10 text-xl font-bold">{title}</h2><p className="mt-4 text-sm leading-6 text-mist">{body}</p></article>)}</div><div className="mt-16 grid gap-10 rounded-[1.8rem] border border-white/[0.09] bg-panel/60 p-7 lg:grid-cols-2 lg:p-10"><div><span className="eyebrow">Customer control</span><h2 className="mt-6 text-3xl font-black">Your account never leaves your hands.</h2><p className="mt-5 text-sm leading-6 text-mist">Coaches work through observation, explanation, replay analysis, and guided sessions. Highground never needs your password, Steam Guard code, recovery code, or remote access to your account.</p></div><div><span className="eyebrow">Completion and support</span><ul className="mt-6 space-y-3">{["Coach submits agreed deliverables", "Customer receives a review window", "Support can join the order when requested", "Refund and dispute decisions are documented", "Coach payment is released after completion and review"].map((item) => <li key={item} className="flex gap-3 text-sm"><Check className="size-4 shrink-0 text-cyan" />{item}</li>)}</ul></div></div><div className="mt-16 flex flex-col items-center text-center"><LifeBuoy className="size-7 text-amber" /><h2 className="mt-5 text-3xl font-black">Clear process. Human support.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-mist">If delivery changes or the fit is not right, support can review the workspace, adjust assignment, and document the resolution.</p><LinkButton href="/pricing" className="mt-7" arrow>Build my plan</LinkButton></div></section></>;
}
