import type { Metadata } from "next";
import { Check, CreditCard, LifeBuoy, MessagesSquare, Search, Star } from "lucide-react";
import { PageHero } from "@/components/ui/page-hero";
import { LinkButton } from "@/components/ui/button";

export const metadata: Metadata = { title: "How Dota 2 Boosting Works", description: "See how boost configuration, compatibility checks, secure payment, booster assignment, party queue, progress, reviews, and support work.", alternates: { canonical: "/how-it-works" } };
const phases = [[Search, "Configure the boost", "Choose a service, current and target rank, role, region, package size, and queue format."], [CreditCard, "Pay securely", "The server validates pricing and discounts, then Stripe calculates tax and hosts checkout."], [MessagesSquare, "Enter your workspace", "A compatible verified booster is assigned and confirms the first customer-controlled queue window."], [Star, "Track and review", "See completed wins, request support, open receipts, and leave verified feedback after delivery."]] as const;

export default function HowItWorksPage() {
  return <><PageHero eyebrow="How it works" title="From rank target to party queue." description="A transparent self-play delivery flow designed around compatibility, account safety, and match-level progress." /><section className="section-pad container-shell"><div className="grid gap-5 lg:grid-cols-4">{phases.map(([Icon, title, body], index) => <article key={title} className="surface rounded-[1.5rem] p-6"><div className="flex items-center justify-between"><Icon className="size-5 text-cyan" /><span className="text-xs font-black text-crimson">0{index + 1}</span></div><h2 className="mt-10 text-xl font-black">{title}</h2><p className="mt-4 text-sm leading-6 text-mist">{body}</p></article>)}</div><div className="mt-16 grid gap-10 rounded-[1.8rem] border border-white/[0.09] bg-panel/60 p-7 lg:grid-cols-2 lg:p-10"><div><span className="eyebrow">Customer-controlled play</span><h2 className="mt-6 text-3xl font-black">Your account never leaves your hands.</h2><p className="mt-5 text-sm leading-6 text-mist">Boosters queue on their own accounts and play alongside you. Highground never needs your password, Steam Guard code, recovery code, device session, or remote access.</p></div><div><span className="eyebrow">Completion and support</span><ul className="mt-6 space-y-3">{["Assisted matches are logged against the package", "Customer sees the remaining milestone count", "Support can join the workspace when requested", "Refund and dispute decisions require audit reasons", "Booster payment is reviewed after completion"].map((item) => <li key={item} className="flex gap-3 text-sm"><Check className="size-4 shrink-0 text-cyan" />{item}</li>)}</ul></div></div><div className="mt-16 flex flex-col items-center text-center"><LifeBuoy className="size-7 text-amber" /><h2 className="mt-5 text-3xl font-black">Clear process. Human support.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-mist">If compatibility, scheduling, or delivery changes, support can review the order, replace an assignment, and document the resolution.</p><LinkButton href="/pricing" className="mt-7" arrow>Configure my boost</LinkButton></div></section></>;
}
