import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CalendarDays, Check, Clock3, Globe2, Languages, MessageSquareText, Star } from "lucide-react";
import { coaches, reviews } from "@/lib/data/content";
import { formatCurrency } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { LinkButton } from "@/components/ui/button";

interface Props { params: Promise<{ slug: string }> }
export function generateStaticParams() { return coaches.map((coach) => ({ slug: coach.slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const coach = coaches.find((item) => item.slug === slug); return coach ? { title: `${coach.displayName} — Dota 2 Coach`, description: coach.biography, alternates: { canonical: `/coaches/${coach.slug}` } } : {}; }

export default async function CoachProfilePage({ params }: Props) {
  const { slug } = await params;
  const coach = coaches.find((item) => item.slug === slug);
  if (!coach) notFound();
  const coachReviews = reviews.filter((review) => review.coach === coach.displayName);
  return (
    <><section className="border-b border-white/[0.07] py-16 md:py-24"><div className="container-shell grid gap-10 lg:grid-cols-[1fr_360px] lg:items-end"><div className="flex flex-col gap-6 sm:flex-row sm:items-start"><span className="grid size-28 shrink-0 place-items-center rounded-[2rem] border border-crimson/25 bg-crimson/10 text-3xl font-black text-[#ef9a9a]">{coach.initials}</span><div><div className="flex flex-wrap items-center gap-3"><Badge tone="cyan">✓ Verified coach</Badge><Badge tone={coach.tier === "Elite" ? "gold" : "neutral"}>{coach.tier}</Badge></div><h1 className="display-type mt-5 text-6xl font-black uppercase md:text-8xl">{coach.displayName}</h1><p className="mt-3 text-base text-mist">{coach.currentRank} · Peak {coach.peakRank}</p></div></div><aside className="surface rounded-2xl p-6"><div className="flex items-center justify-between"><span className="text-xs text-mist">Starting at</span><strong className="text-2xl">{formatCurrency(coach.startingPrice)}</strong></div><LinkButton href={`/pricing?coach=${coach.slug}`} className="mt-5 w-full" arrow>Build a session</LinkButton><p className="mt-3 text-center text-[0.62rem] text-mist">Availability confirmed before assignment</p></aside></div></section>
      <section className="section-pad container-shell grid gap-14 lg:grid-cols-[1fr_360px]"><div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[[Star, `${coach.rating} rating`], [MessageSquareText, `${coach.sessions} sessions`], [Globe2, coach.region], [Clock3, coach.availability]].map(([Icon, label]) => { const ProfileIcon = Icon as typeof Star; return <div key={label as string} className="rounded-xl border border-white/[0.08] bg-panel/50 p-4"><ProfileIcon className="size-4 text-cyan" /><p className="mt-3 text-xs font-bold">{label as string}</p></div>; })}</div><div className="mt-12"><span className="eyebrow">About the coach</span><h2 className="mt-6 text-3xl font-black">A clear framework, adapted to the player.</h2><p className="mt-5 max-w-3xl text-base leading-7 text-mist">{coach.biography}</p><p className="mt-4 max-w-3xl text-base leading-7 text-mist">{coach.coachingStyle}</p></div><div className="mt-12 grid gap-8 sm:grid-cols-2"><div><p className="text-xs font-bold tracking-wider text-amber uppercase">Role expertise</p><div className="mt-4 flex flex-wrap gap-2">{coach.roles.map((item) => <Badge key={item}>{item}</Badge>)}</div></div><div><p className="text-xs font-bold tracking-wider text-amber uppercase">Specialties</p><div className="mt-4 flex flex-wrap gap-2">{coach.specialties.map((item) => <Badge key={item}>{item}</Badge>)}</div></div></div>{coachReviews.length ? <div className="mt-14"><span className="eyebrow">Verified feedback</span>{coachReviews.map((review) => <blockquote key={review.id} className="mt-6 rounded-2xl border border-white/[0.08] bg-panel/60 p-6 text-base leading-7">“{review.quote}”<footer className="mt-4 text-xs text-mist">{review.customer} · {review.service} · Verified paid order</footer></blockquote>)}</div> : null}</div>
        <aside className="space-y-4"><div className="surface rounded-2xl p-5"><p className="text-xs font-bold tracking-wider text-amber uppercase">Profile details</p><div className="mt-5 space-y-4 text-sm"><div className="flex gap-3"><Languages className="size-4 text-cyan" /><span>{coach.languages.join(" · ")}</span></div><div className="flex gap-3"><Globe2 className="size-4 text-cyan" /><span>{coach.region}<br /><small className="text-mist">{coach.timeZone}</small></span></div><div className="flex gap-3"><CalendarDays className="size-4 text-cyan" /><span>Next availability: {coach.availability}</span></div></div></div><div className="rounded-2xl border border-white/[0.08] p-5"><p className="text-xs font-bold tracking-wider uppercase">What every order includes</p><ul className="mt-4 space-y-3 text-xs text-mist">{["Private order workspace", "Secure scheduling", "Coach deliverables", "Support access"].map((item) => <li key={item} className="flex gap-2"><Check className="size-3.5 text-cyan" />{item}</li>)}</ul></div></aside>
      </section></>
  );
}
