import { CalendarDays, CreditCard, Home, MessageSquareText, PackageCheck, Settings, Swords, Target, Trophy, UserRound, WalletCards } from "lucide-react";
import { PortalShell, type PortalNavItem } from "@/components/portal/portal-shell";
import { MetricCard } from "@/components/portal/metric-card";
import { requireRole } from "@/lib/auth/require-role";
import { LinkButton } from "@/components/ui/button";

export const dynamic = "force-dynamic";

const nav: PortalNavItem[] = [{ label: "Overview", href: "/dashboard", icon: Home, active: true }, { label: "My boosts", href: "/dashboard/orders/demo-order", icon: PackageCheck }, { label: "Messages", href: "/dashboard/orders/demo-order#messages", icon: MessageSquareText, badge: "2" }, { label: "Queue schedule", href: "/dashboard#schedule", icon: CalendarDays }, { label: "Progress", href: "/dashboard#progress", icon: Trophy }, { label: "Boosters", href: "/boosters", icon: UserRound }, { label: "Billing", href: "/dashboard/billing", icon: WalletCards }, { label: "Settings", href: "/dashboard#settings", icon: Settings }];

export default async function CustomerDashboardPage() {
  const user = await requireRole(["customer"]);
  return <PortalShell user={user} label="Customer" navigation={nav}>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[0.62rem] font-bold tracking-[0.13em] text-amber uppercase">Thursday · Active climb</p><h1 className="mt-2 text-3xl font-black">Good afternoon, {user.displayName}.</h1><p className="mt-2 text-sm text-mist">Your next queue, remaining wins, booster messages, and billing are all here.</p></div><LinkButton href="/pricing" className="shrink-0">Start another boost</LinkButton></div>
    <div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={PackageCheck} label="Active boosts" value="1" detail="Legend III → Ancient I" tone="red" /><MetricCard icon={Trophy} label="Wins delivered" value="7 / 10" detail="3 remaining" tone="gold" /><MetricCard icon={CalendarDays} label="Next queue" value="Fri 7:30" detail="America/Toronto" tone="cyan" /><MetricCard icon={MessageSquareText} label="Unread messages" value="2" detail="From Northstar" /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[0.6rem] font-bold tracking-wider text-amber uppercase">Rank boost · HG-4281</p><h2 className="mt-2 text-xl font-black">Legend III → Ancient I</h2></div><span className="rounded-full border border-cyan/20 bg-cyan/[0.06] px-2.5 py-1 text-[0.58rem] font-bold text-cyan uppercase">In progress</span></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/[0.07]"><div className="h-full w-[70%] bg-gradient-to-r from-crimson via-amber to-cyan" /></div><div className="mt-2 flex justify-between text-[0.6rem] text-mist"><span>7 of 10 assisted wins complete</span><span>70%</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-white/[0.07] p-4"><Swords className="size-4 text-cyan" /><p className="mt-3 text-xs font-bold">Northstar assigned</p><p className="mt-1 text-[0.62rem] text-mist">Elite · Carry / Mid</p></div><div className="rounded-xl border border-white/[0.07] p-4"><Target className="size-4 text-amber" /><p className="mt-3 text-xs font-bold">Current milestone</p><p className="mt-1 text-[0.62rem] text-mist">3 wins remaining</p></div></div><LinkButton href="/dashboard/orders/demo-order" variant="secondary" className="mt-5">Open workspace</LinkButton></section><section className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><p className="text-sm font-black">Pending actions</p><div className="mt-5 space-y-3">{[[CalendarDays, "Confirm Friday queue", "Due today"], [Trophy, "Review win milestone 7", "Ready now"], [CreditCard, "Receipt available", "Paid Jul 11"]].map(([Icon, title, detail]) => { const ActionIcon = Icon as typeof CalendarDays; return <div key={title as string} className="flex items-center gap-3 rounded-xl border border-white/[0.07] p-3"><ActionIcon className="size-4 text-mist" /><div><p className="text-xs font-bold">{title as string}</p><p className="mt-1 text-[0.58rem] text-mist">{detail as string}</p></div></div>; })}</div><LinkButton href="/dashboard/billing" variant="ghost" className="mt-4 w-full">Open billing</LinkButton></section></div>
  </PortalShell>;
}
