import { CalendarDays, CreditCard, Home, MessageSquareText, PackageCheck, Settings, Swords, Target, Trophy, UserRound, WalletCards } from "lucide-react";
import { PortalShell, type PortalNavItem } from "@/components/portal/portal-shell";
import { MetricCard } from "@/components/portal/metric-card";
import { requireRole } from "@/lib/auth/require-role";
import { LinkButton } from "@/components/ui/button";
import { getCustomerOrders } from "@/lib/portal/customer-orders";

export const dynamic = "force-dynamic";

const nav: PortalNavItem[] = [{ label: "Overview", href: "/dashboard", icon: Home, active: true }, { label: "My boosts", href: "/dashboard/orders", icon: PackageCheck }, { label: "Messages", href: "/dashboard/orders", icon: MessageSquareText }, { label: "Queue schedule", href: "/dashboard/orders", icon: CalendarDays }, { label: "Progress", href: "/dashboard/orders", icon: Trophy }, { label: "Boosters", href: "/boosters", icon: UserRound }, { label: "Billing", href: "/dashboard/billing", icon: WalletCards }, { label: "Settings", href: "/dashboard#settings", icon: Settings }];

export default async function CustomerDashboardPage() {
  const user = await requireRole(["customer"]);
  const orders = await getCustomerOrders(user.id);
  const activeOrder = orders.find((order) => ["paid", "matching", "coach_assigned", "awaiting_customer", "in_progress", "delivery_submitted", "customer_review"].includes(order.status));
  const completedCount = orders.filter((order) => order.status === "completed").length;
  if (!activeOrder) return <PortalShell user={user} label="Customer" navigation={nav}><div className="max-w-2xl py-7"><p className="text-[0.62rem] font-bold tracking-[0.13em] text-amber uppercase">Dota 2 command center</p><h1 className="mt-3 text-3xl font-black">Good afternoon, {user.displayName}.</h1><p className="mt-3 text-sm leading-6 text-mist">Your portal is ready. When you start a boost, this becomes your live board for milestones, queue scheduling, messages, receipts, and support.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><LinkButton href="/pricing" arrow>Configure an MMR boost</LinkButton><LinkButton href="/dashboard/orders" variant="secondary">View my boosts</LinkButton></div></div></PortalShell>;
  return <PortalShell user={user} label="Customer" navigation={nav}>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[0.62rem] font-bold tracking-[0.13em] text-amber uppercase">Active Dota 2 delivery</p><h1 className="mt-2 text-3xl font-black">Good afternoon, {user.displayName}.</h1><p className="mt-2 text-sm text-mist">Your milestones, delivery state, receipts, and support are all here.</p></div><LinkButton href="/pricing" className="shrink-0">Start another boost</LinkButton></div>
    <div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={PackageCheck} label="Active boosts" value={String(orders.filter((order) => !["completed", "cancelled", "refunded"].includes(order.status)).length)} detail={activeOrder.serviceName} tone="red" /><MetricCard icon={Trophy} label="Milestones complete" value={activeOrder.totalMilestones ? `${activeOrder.completedMilestones} / ${activeOrder.totalMilestones}` : "—"} detail={activeOrder.totalMilestones ? `${activeOrder.progressPercent}% tracked` : "Awaiting setup"} tone="gold" /><MetricCard icon={CalendarDays} label="Delivery state" value={activeOrder.status.replaceAll("_", " ")} detail={activeOrder.scope} tone="cyan" /><MetricCard icon={MessageSquareText} label="Completed boosts" value={String(completedCount)} detail="Delivery history" /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[0.6rem] font-bold tracking-wider text-amber uppercase">{activeOrder.publicReference} · {activeOrder.serviceName}</p><h2 className="mt-2 text-xl font-black">{activeOrder.scope}</h2></div><span className="rounded-full border border-cyan/20 bg-cyan/[0.06] px-2.5 py-1 text-[0.58rem] font-bold text-cyan uppercase">{activeOrder.status.replaceAll("_", " ")}</span></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/[0.07]"><div className="h-full bg-gradient-to-r from-crimson via-amber to-cyan" style={{ width: `${activeOrder.progressPercent}%` }} /></div><div className="mt-2 flex justify-between text-[0.6rem] text-mist"><span>{activeOrder.totalMilestones ? `${activeOrder.completedMilestones} of ${activeOrder.totalMilestones} milestones complete` : "Milestones will appear after operations setup."}</span><span>{activeOrder.progressPercent}%</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-white/[0.07] p-4"><Swords className="size-4 text-cyan" /><p className="mt-3 text-xs font-bold">Customer-controlled delivery</p><p className="mt-1 text-[0.62rem] text-mist">Queue details remain attached to your private order workspace.</p></div><div className="rounded-xl border border-white/[0.07] p-4"><Target className="size-4 text-amber" /><p className="mt-3 text-xs font-bold">Live milestone board</p><p className="mt-1 text-[0.62rem] text-mist">Every completed milestone is reflected here as operations records it.</p></div></div><LinkButton href={`/dashboard/orders/${activeOrder.id}`} variant="secondary" className="mt-5">Open workspace</LinkButton></section><section className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><p className="text-sm font-black">Order actions</p><div className="mt-5 space-y-3">{[[CalendarDays, "View delivery workspace", "Milestones and messages"], [Trophy, "Track progress", activeOrder.totalMilestones ? `${activeOrder.progressPercent}% complete` : "Pending setup"], [CreditCard, "Receipts and billing", "Payment records"]].map(([Icon, title, detail]) => { const ActionIcon = Icon as typeof CalendarDays; return <div key={title as string} className="flex items-center gap-3 rounded-xl border border-white/[0.07] p-3"><ActionIcon className="size-4 text-mist" /><div><p className="text-xs font-bold">{title as string}</p><p className="mt-1 text-[0.58rem] text-mist">{detail as string}</p></div></div>; })}</div><LinkButton href="/dashboard/billing" variant="ghost" className="mt-4 w-full">Open billing</LinkButton></section></div>
  </PortalShell>;
}
